// app/seo.ts
import { initSeo } from "remix-seo";
export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
  // Pass any SEO defaults for your site here.
  // If individual routes do not provide their own meta and link tags,
  // the tags generated by the defaults will be used.
  title: "MakeBitByte",
  titleTemplate: "%s | MakeBitByte",
  description: "A blog created with Remix-run and Tailwind.css",
  openGraph: {
    url: "https://www.makebitbyte.com",
    type: "website",
    siteName: "MakeBitByte",
    description: "Musings of a restless mind",
    title: "MakeBitByte",
    // images: [{ url: "", alt: "" }],
  },
  twitter: {
    title: "MakeBitByte",
    card: "summary_large_image",
    site: "https://www.makebitbyte.com",
    description: "Musings of a restless mind",
    //  image: { url: "", alt: "" }
  },
});
